### PR TITLE
Upgrade puppet-brewcask dependency

### PR DESCRIPTION
**Pull request by jabley**
It looks like something has changed in the ecosystem. I started seeing
errors running `boxen`:

```
Error: Execution of 'brew boxen-latest brew-cask' returned 1: Error: No available formula with the name "brew-cask"
Error: /Stage[main]/Brewcask/Package[brew-cask]/ensure: change from absent to present failed: Execution of 'brew boxen-latest brew-cask' returned 1: Error: No available formula with the name "brew-cask"
```

And all of my `boxen::personal::osx_apps` would be skipped.

This change reflects the fact that `cask` now comes with `brew` now.

### CODE REVIEW

**Comment by jabley** [comment]
Fixes #824.

**Comment by jacobbednarz** [comment]
I'm not convinced this is going to solve the issue as the version bump only manages the [brewcask tasks within homebrew itself](https://github.com/boxen/puppet-brewcask/compare/d3a96ee...b8b35ad3cc86868e29edc41ecb7e7a64d3a24fff). Would you be able to elaborate a little more on your reasoning here? I'm all for getting this updated regardless but I don't want to close off #824 if it's not related.

Have you also tried `brew update && brew upgrade` to ensure it's not something to do with an outdated homebrew installation?

**Comment by happicamper** [comment]
Had experienced that last week but after seeing the latest puppet-brewcask version, I changed my Puppetfile same as the changes of @jabley then it solves the problem.

**Comment by jacobbednarz** [comment]
My side thought here is that the Puppetfile change _may_ have initiated the update/upgrade itself so version bumping was an indirect fix. Does that make sense? For what it's worth, I haven't delved too deep into that code (yet!) but plan to in the coming months so either way I'm happy here.

**Comment by jabley** [comment]
`brew update && brew upgrade` had not fixed this for me, hence the reason I went digging and found the change in the puppet module.

Also saw the problem on multiple machines.

**Pull request merged**
