### PR TITLE
Add facts.d and boxen::personal config & docs

### PR DESCRIPTION
**Pull request by dgoodlad**
Updates the boxen and homebrew modules, and documents the usage of some of their more recent features. Notably:

* `facts.d` [external facts](https://docs.puppetlabs.com/facter/2.2/custom_facts.html#external-facts) support
* `boxen::personal::*` from boxen/puppet-boxen#119

In addition, this adds boxen/puppet-brewcask as a core dependency, to support the `boxen::personal::osx_apps` key. Big thanks to @phinze for writing this module, and for giving the :+1: to adopt it into core boxen

### CODE REVIEW

**Comment by petems** [comment]
Does this mean boxen can now work with a brew install outside of `/opt/boxen/brew`? Because that's the biggest problem I have with convincing people do use on a pre-existing machine is having to nuke their old brew install...

**Comment by rafaelfranca** [comment]
@petems yes, now it can

**Comment by rafaelfranca** [comment]
@dgoodlad looks good. :shipit:

**Comment by petems** [comment]
@rafaelfranca :star: Awesome!

**Pull request merged**
