### PR TITLE
Update core module versions

### PR DESCRIPTION
**Pull request by sgerrand**
:information_desk_person: When setting up a new `boxen` install, I noticed quite a few core Puppet modules were out of date. These changes update the versions of those modules to synchronise them with the latest available tag.

### CODE REVIEW

**Comment by rafaelfranca** [comment]
The lockfile and the cache need to be updated too. Could you run script/bootstrap and add these changes?

**Comment by sgerrand** [comment]
@rafaelfranca: Apologies, will do. :ok_woman:

**Comment by sgerrand** [comment]
@rafaelfranca: Done. :recycle:

**Comment by sgerrand** [comment]
@mikemcquaid, @rafaelfranca: Would you please review these changes. :wave:

**Comment by rafaelfranca** [comment]
Thank you

**Comment by sgerrand** [comment]
:bow:

**Pull request merged**
