### PR TITLE
Bump Boxen gem for 10.11

### PR DESCRIPTION
**Pull request by timdorr**
In theory, if you have this and boxen/boxen-web@9f9ff259 or higher, you should be good to go with El Capitan.

### CODE REVIEW

**Comment by rafaelfranca** [comment]
:shipit:

**Comment by jacobbednarz** [comment]
:ship:

**Comment by joneslee85** [comment]
:+1:

**Comment by oratthumzap** [comment]
just spent an entire day on this issue.
was solved by applying these changes.
please merge this commit ASAP so that everyone can enjoy the wonder of boxen on El Capitan ;)

**Comment by sjoeboo** [comment]
+1

**Pull request merged**
