### PR TITLE
Fix CI details

### PR DESCRIPTION
**Pull request by jacobbednarz**
Pulls over the commits from #861 and use the secure credentials and
_actually_ run successfully.

### CODE REVIEW

**Comment by jacobbednarz** [comment]
OK, so the last failure is a legit one due to GitHub disabling older versions of TLS and I've outlined at https://github.com/boxen/boxen/issues/221. I'm still working on this but will post some updates there.

**Comment by jacobbednarz** [comment]
This PR is going to be blocked until I've fixed Boxen to be High Sierra only (per https://github.com/boxen/boxen/issues/221#issuecomment-369721631).

**Comment by jacobbednarz** [comment]
@n0ts I've removed your changes to the `gemrc` file (via d5ed644) since that don't have any impact on whether or not we can connect to a service that is TLSv1.2 enabled.

The only fix that will move this forward is upgrading to High Sierra and fixing the issues mentioned at boxen/boxen#222

**Comment by n0ts** [comment]
Sorry, Thanks.
Now CI error is `tlsv1`, so I think that if boxen support 10.13 it will cure naturally.

I'll send new PR support 10.13, Could you open issue about support 10.13 at boxen/boxen?

**Comment by jacobbednarz** [comment]
Fixed in #863

**Pull request closed without merging**
